name: signdoc
description: A Flutter package for PDF viewing and signing with signature pad support.
version: 1.0.5
homepage: https://github.com/RiadhG-Hub/signdoc
repository: https://github.com/RiadhG-Hub/signdoc
issue_tracker: https://github.com/RiadhG-Hub/signdoc/issues/
documentation: https://github.com/RiadhG-Hub/signdoc#readme

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.4.1+1
  syncfusion_flutter_pdf: ^31.1.17
  syncfusion_flutter_signaturepad: ^31.1.17


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
# If you plan to ship images or fonts later, add them here
