name: signdoc
description: A Flutter package for PDF viewing and signing with signature pad support.
version: 1.0.0
homepage: https://github.com/RiadhG-Hub/signdoc
repository: https://github.com/RiadhG-Hub/signdoc
issue_tracker: https://github.com/RiadhG-Hub/signdoc/issues
documentation: https://github.com/RiadhG-Hub/signdoc#readme

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  bloc: ^9.0.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_pdfview: ^1.4.1+1
  path_provider: ^2.1.5
  syncfusion_flutter_pdf: ^30.2.7
  syncfusion_flutter_signaturepad: ^30.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
# If you plan to ship images or fonts later, add them here
